project_id = "tnzgpzablwfptagfbnvb"

[functions.get-next-agent]
verify_jwt = false

[functions.meta-lead-webhook]
verify_jwt = false

[functions.test-scrape-images]
verify_jwt = false

[functions.scrape-product-images]
verify_jwt = false

[functions.scrape-all-products]
verify_jwt = false

[functions.scraping-status]
verify_jwt = false

[functions.make-webhook-proxy]
verify_jwt = false

[functions.check-invoice-deadlines]
verify_jwt = false

[functions.disqualified-lead-webhook]
verify_jwt = false

[functions.sync-inmovilla-products]
verify_jwt = false

[functions.fix-unassigned-leads]
verify_jwt = false
