project_id = "tnzgpzablwfptagfbnvb"

[functions.get-next-agent]
verify_jwt = false

[functions.test-scrape-images]
verify_jwt = false

[functions.scrape-product-images]
verify_jwt = false

[functions.scrape-all-products]
verify_jwt = false

[functions.scraping-status]
verify_jwt = false

[functions.sync-inmovilla]
verify_jwt = false
